package br.com.ifce.model.enums;

public enum TipoColeta {

	ASPIRADO_TRAQUEAL,
	ESCARRO,
	LAVADO_BRONCOALVEOLAR,
	ASPIRADO_BRONQUICO,
	ASPIRADO_NASO_FARINGIEO,
	SWAB_OROFARINGE_NASOFARINGE,
	SECRECAO_TRAQUEAL,
	SWAB_DE_NASOFARINGE;
	
}
